3_Junior/Semester_1/PSI/P4/P4_5/core/urls.py
from django.urls import path
from core import views

app_name = 'core'

# It creates a relation between the url and the view
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('applygroup/', views.applygroup, name='applygroup'),
    path('applypair/', views.applypair, name='applypair'),
    path('convalidation/', views.convalidation, name='convalidation'),
    path('breakpair/', views.breakpair, name='breakpair'),
]

3_Junior/Semester_1/PSI/P4/P4_5/labassign/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

# It creates a relation between the url and the view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

3_Junior/Semester_1/PSI/P4/P4_5/templates/applygroup.html
{% extends "base.html" %} {% block title %} Apply Group {% endblock%} {% block body %} {% if date is False %}
<h3>Group selection is not active</h3>
{% elif group_user is None%}
<p>In this page you can choose which lab group you would like to be part of. Take into acount that if you have already a valid pair then your partner will automatically be added to the group you select too. Lab groups have limited space so take that into
    account too.</p>
<form id="group_form" method="post" action="{% url 'core:applygroup' %}" enctype="multipart/form-data">

    {% csrf_token %}

    <!-- Display each form -->
    {{ group_form.as_p }}

    <!-- Provide a button to click to submit the form. -->
    <input type="submit" class="btn btn-primary" value="Submit" />
</form>
{% else %}
<h3>You belong to group <b>{{group_user}}</b></h3>
{% endif %} {% endblock %}

3_Junior/Semester_1/PSI/P4/P4_5/templates/applypair.html
{% extends "base.html" %} {% block title %} Apply Pair {% endblock%} {% block body %} {% if pair_user is None %}
<p>
    The selection of a pair requires two steps. First you select a student to be paired with. In that moment the pair is created but is not validated. Then the other student has to do the same with you and in that moment the pair gets validated.
</p>

<form id="pair_form" method="post" action="{% url 'core:applypair' %}" enctype="multipart/form-data">

    {% csrf_token %}

    <!-- Display each form -->
    {{ pair_form.as_p }}

    <!-- Provide a button to click to submit the form. -->
    <input type="submit" class="btn btn-primary" value="Submit" />
</form>
{% elif pair_user.validated is True %}
<h3>You already belong to pair {{pair_user.student1}}, {{pair_user.student2}}</h3>
{% else %}
<h3>You have requested to be paired with <b>{{pair_user.student2}}</b></h3>
{% endif %} {% endblock %}

3_Junior/Semester_1/PSI/P4/P4_5/templates/base.html
<!DOCTYPE html> {% load staticfiles %}
<html>

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    <script src="{% static 'js/main.js' %}"></script>
    <link rel="icon" href="{% static 'img/icon.png' %}">
    <title>
        EDAT - {{ title }}
    </title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>


<body>
    <header>
        <div class="w3-bar w3-border w3-black">
            <a href="{% url 'core:home' %}"><button class="w3-bar-item w3-button">Home</button></a>
            <a href="{% url 'core:login' %}"><button class="w3-bar-item w3-button w3-hover-none w3-text-grey w3-hover-text-white">LogIn</button></a> {% if user.is_authenticated %}
            <a href="{% url 'core:logout' %}"><button class="w3-bar-item w3-button w3-hover-none w3-text-grey w3-hover-text-white">LogOut</button></a>
            <a href="{% url 'core:convalidation' %}"><button class="w3-bar-item w3-button w3-hover-none w3-text-grey w3-hover-text-white">Convalidation</button></a>
            <a href="{% url 'core:applypair' %}"><button class="w3-bar-item w3-button w3-hover-none w3-text-grey w3-hover-text-white">Apply Pair</button></a>
            <a href="{% url 'core:breakpair' %}"><button class="w3-bar-item w3-button w3-hover-none w3-text-grey w3-hover-text-white">Break Pair</button></a>
            <a href="{% url 'core:applygroup' %}"><button class="w3-bar-item w3-button w3-hover-none w3-text-grey w3-hover-text-white">Apply Group</button></a> {% endif %}
        </div>
    </header>
    <div class="container">
        <h1>{{ title }}</h1>
        {% block body %} {% endblock %}
    </div>
    <footer class="footer">
        Designed by 
        <br>
        <b>All rights reserved © 2020 PSI UAM</b>
    </footer>
</body>

</html>

3_Junior/Semester_1/PSI/P4/P4_5/templates/breakpair.html
{% extends "base.html" %} {% block title %} Break Pair {% endblock%} {% block body %}
<p>Here you can check the pairs you are part of. You can request to break this pairs, if the pair is validated you will send a request to break it, if both members of the pair request the break it will be broken. If the pair is not validated it will be broken
    directly with your request.</p>

{% if bad_data is True %}
<p>
    <h3><b>The data you send is incorrect, please send the correct data</b></h3>
</p>
{% endif %} {% if pair_delete is True %}
<p>
    <h3><b>Pair broken successfully</b></h3>
</p>
{% endif %} {% if pair_request is True %}
<p>
    <h3><b>Your request to delete the pair has been submitted successfully</b></h3>
</p>
{% endif %}

<h3>Select the pair to be broken</h3>
<form id="breakpair_form" method="post" action="{% url 'core:breakpair' %}" enctype="multipart/form-data">

    {% csrf_token %}

    <!-- Display each form -->
    {{ breakpair_form.as_p }}

    <!-- Provide a button to click to submit the form. -->
    <input type="submit" class="btn btn-primary" value="Submit" />
</form>
{% endblock %}

3_Junior/Semester_1/PSI/P4/P4_5/templates/convalidation.html
{% extends "base.html" %} {% block title %} Convalidation {% endblock%} {% block body %}
<p>Here you can check if you satisfy the requeriments needed to convalidate the EDAT assigments with the marks of the last year.</p>{% if conv is not None %} {% if conv is True %}
<h3>Convalidation <b>CONFIRMED</b>, You satisfy the requirements</h3>
{% else %}

<h3>Convalidation <b>DENIED</b>, do not satisfy requirements</h3>
{% endif %} {% elif pair > 0 %}
<h3>You are a member of a pair, break it before applying for convalidation</h3>
{% endif %} {% endblock %}

3_Junior/Semester_1/PSI/P4/P4_5/templates/home.html
{% extends "base.html" %} {% block body %} {% if user.is_authenticated %} Summary page for <b>{{user.first_name}} {{user.last_name}}</b>. {% if user.theoryGroup != null %} (your theory group is {{user.theoryGroup}}) {%endif%}
<br>
<br>
<h3>Convalidation</h3>
{% if user.convalidationGranted %}
<p>Your lab assignments have been convalidated.</p>
{% else %}
<p>Your lab assignments have NOT been convalidated.</p>
<p>(If you wish to request a convalidation press the "convalidation" button.)</p>
{% endif %}

<p>
    <h3>Pair Status</h3>
    {% if pair is not None %} You are part of the following pair
    <ul>
        <li>{{pair.student1}}</li>
        <li>{{pair.student2}}</li>
    </ul>
    {% if pair.validated %} The pair is active {% else %} The pair is NOT active {% endif %} {%else%} You are not part of any pair yet. {%endif%}
</p>

<h3>Selected Group</h3>
{% if user.labGroup != null %} Your Lab Group is: {{user.labGroup}} {%else%} You are not part of a Lab Group yet.{%endif%}
<hr>{% endif %}
<h3>Help?</h3>
<br> <b>This web site allows EDAT students to select which laboratory group they wish to enroll in. Please follow the steps below</b>
<ol>
    <li><a href="{% url 'core:login' %}">Login</a> with your institutional NIA as username, and your NIE as password</li>
    {% if user.is_authenticated %}
    <li>Check your <a href="{% url 'core:convalidation' %}">convalidation</a> state if needed</li>
    <li><a href="{% url 'core:applypair' %}">Select a partner</a> to be with during the assignments</li>
    <li>If you no longer want to be with that partner you can <a href="{% url 'core:breakpair' %}">break the pair<a></li>
    <li> <a href="{% url 'core:applygroup' %}">Select a lab group<a> among the ones offered depending on your theory group</li>
    {% endif %}
</ol>

{% endblock %}

3_Junior/Semester_1/PSI/P4/P4_5/templates/login.html
{% extends "base.html" %} {% block title %} Login {% endblock%} {% block body %} {% if user.is_authenticated %}
<div><b>{{user.first_name}}</b> you are already logged in, logout if you want to login with another user</div>
{% else %}
<p>Insert your institutional NIA as username and your NIE as password to see your data and access the services of the page.</p>
<form method="post" action="{% url 'core:login' %}">
    {% csrf_token %}
    <h2>Please login</h2>
    <p><label for="id_username">Username:</label> <input type="text" name="username" autofocus="" required="" id="id_username"></p>
    <p><label for="id_password">Password:</label> <input type="password" name="password" required="" id="id_password">
    </p>
    <input type="submit" class="btn btn-primary" value="LogIn">
</form>

{% if wrong_login %}
<div>Username or password incorrect
</div>
{% endif %} {% endif %} {% endblock %}

3_Junior/Semester_1/PSI/P4/P4_5/templates/logout.html
{% extends "base.html" %}

{% block title %}
Logout
{% endblock%}

{% block body %}
Logout succesfully
{% endblock %}